export const contentCardVariants = {
  root: [
    "group",
    "relative",
    "overflow-hidden",
    "rounded-[var(--radius-large)]",
    "border",
    "border-border",
    "bg-background/80",
    "p-8",
    "shadow-[var(--shadow-card)]",
    "backdrop-blur-sm",
    "transition-all",
    "duration-500",
    "before:absolute",
    "before:inset-x-0",
    "before:top-0",
    "before:h-px",
    "before:origin-left",
    "before:scale-x-0",
    "before:bg-brand",
    "before:transition-transform",
    "before:duration-500",
    "hover:-translate-y-1",
    "hover:border-brand/25",
    "hover:shadow-[var(--shadow-overlay)]",
    "hover:before:scale-x-100",
  ].join(" "),
} as const;