export const analysisResultsVariants = {
  section: [
    "rounded-[var(--radius-large)]",
    "border",
    "border-border",
    "bg-background",
    "p-6",
    "shadow-[var(--shadow-card)]",
  ].join(" "),
  heading: [
    "text-xl",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  list: [
    "mt-5",
    "flex",
    "flex-col",
    "gap-6",
  ].join(" "),
  result: [
    "rounded-[var(--radius-medium)]",
    "border",
    "border-border",
    "bg-surface-muted",
    "p-5",
  ].join(" "),
  filename: [
    "break-words",
    "text-lg",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  summary: [
    "mt-4",
    "grid",
    "gap-3",
    "sm:grid-cols-2",
  ].join(" "),
  metric: [
    "rounded-[var(--radius-small)]",
    "border",
    "border-border",
    "bg-background",
    "p-4",
  ].join(" "),
  metricLabel: [
    "text-xs",
    "font-semibold",
    "uppercase",
    "tracking-[var(--letter-spacing-label)]",
    "text-muted-foreground",
  ].join(" "),
  metricValue: [
    "mt-1",
    "text-2xl",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  categories: [
    "mt-4",
    "flex",
    "flex-wrap",
    "gap-2",
  ].join(" "),
  category: [
    "rounded-[var(--radius-pill)]",
    "bg-brand-soft",
    "px-3",
    "py-1",
    "text-xs",
    "font-medium",
    "text-brand",
  ].join(" "),
  warning: [
    "mt-4",
    "rounded-[var(--radius-small)]",
    "border",
    "border-amber-300",
    "bg-amber-50",
    "p-4",
    "text-sm",
    "leading-6",
    "text-foreground",
  ].join(" "),
  empty: [
    "mt-4",
    "text-sm",
    "leading-6",
    "text-muted-foreground",
  ].join(" "),
  block: ["mt-5"].join(" "),
  blockTitle: [
    "mb-3",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  taggedText: [
    "block",
    "max-h-80",
    "overflow-auto",
    "whitespace-pre-wrap",
    "rounded-[var(--radius-small)]",
    "border",
    "border-border",
    "bg-background",
    "p-4",
    "font-mono",
    "text-xs",
    "leading-5",
    "text-foreground",
  ].join(" "),
} as const;
