export const jobResultsVariants = {
  section: [
    "rounded-[var(--radius-large)]",
    "border",
    "border-border",
    "bg-background",
    "p-6",
    "shadow-[var(--shadow-card)]",
  ].join(" "),
  heading: [
    "text-xl",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  job: [
    "mt-5",
    "rounded-[var(--radius-medium)]",
    "border",
    "border-border",
    "bg-surface-muted",
    "p-5",
  ].join(" "),
  jobId: [
    "font-mono",
    "text-xs",
    "text-muted-foreground",
  ].join(" "),
  loading: [
    "mt-3",
    "text-sm",
    "text-muted-foreground",
  ].join(" "),
  error: [
    "mt-3",
    "rounded-[var(--radius-small)]",
    "border",
    "border-destructive/25",
    "bg-destructive/5",
    "p-4",
  ].join(" "),
  errorTitle: [
    "font-semibold",
    "text-destructive",
  ].join(" "),
  errorBody: [
    "mt-1",
    "text-sm",
    "leading-6",
    "text-muted-foreground",
  ].join(" "),
  retry: ["mt-3"].join(" "),
  documents: [
    "mt-4",
    "flex",
    "flex-col",
    "gap-5",
  ].join(" "),
  document: [
    "rounded-[var(--radius-medium)]",
    "border",
    "border-border",
    "bg-background",
    "p-5",
  ].join(" "),
  documentTitle: [
    "break-words",
    "text-lg",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  documentError: [
    "mt-3",
    "text-sm",
    "leading-6",
    "text-destructive",
  ].join(" "),
  result: [
    "mt-5",
    "flex",
    "flex-col",
    "gap-5",
  ].join(" "),
  subsection: [
    "rounded-[var(--radius-small)]",
    "border",
    "border-border",
    "p-4",
  ].join(" "),
  subsectionTitle: [
    "font-semibold",
    "text-foreground",
  ].join(" "),
  summary: [
    "mt-2",
    "leading-7",
    "text-muted-foreground",
  ].join(" "),
  confidence: [
    "mt-2",
    "text-sm",
    "font-medium",
    "text-brand",
  ].join(" "),
} as const;
