export const jobStatusVariants = {
  section: [
    "rounded-[var(--radius-large)]",
    "border",
    "border-border",
    "bg-background",
    "p-6",
    "shadow-[var(--shadow-card)]",
  ].join(" "),
  heading: [
    "text-xl",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  list: [
    "mt-5",
    "grid",
    "gap-4",
    "lg:grid-cols-2",
  ].join(" "),
  card: [
    "rounded-[var(--radius-medium)]",
    "border",
    "border-border",
    "bg-surface-muted",
    "p-5",
  ].join(" "),
  cardHeader: [
    "flex",
    "items-start",
    "justify-between",
    "gap-4",
  ].join(" "),
  identity: ["min-w-0"].join(" "),
  jobId: [
    "truncate",
    "font-mono",
    "text-xs",
    "text-muted-foreground",
  ].join(" "),
  status: [
    "mt-1",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  message: [
    "mt-3",
    "text-sm",
    "leading-6",
    "text-muted-foreground",
  ].join(" "),
  progress: [
    "mt-4",
    "h-2",
    "w-full",
    "overflow-hidden",
    "rounded-[var(--radius-pill)]",
    "bg-border",
    "[&::-webkit-progress-bar]:bg-border",
    "[&::-webkit-progress-value]:bg-brand",
    "[&::-moz-progress-bar]:bg-brand",
  ].join(" "),
  detail: [
    "mt-2",
    "text-xs",
    "text-muted-foreground",
  ].join(" "),
  error: [
    "mt-3",
    "text-sm",
    "leading-6",
    "text-destructive",
  ].join(" "),
} as const;
