export const uploadQueueVariants = {
  root: [
    "rounded-[var(--radius-large)]",
    "border",
    "border-border",
    "bg-background",
    "p-6",
    "shadow-[var(--shadow-card)]",
  ].join(" "),
  header: [
    "flex",
    "items-center",
    "justify-between",
    "gap-4",
  ].join(" "),
  title: [
    "text-xl",
    "font-semibold",
    "text-foreground",
  ].join(" "),
  count: [
    "rounded-[var(--radius-pill)]",
    "bg-brand-soft",
    "px-3",
    "py-1",
    "text-sm",
    "font-medium",
    "text-brand",
  ].join(" "),
  empty: [
    "flex",
    "min-h-56",
    "flex-col",
    "items-center",
    "justify-center",
    "text-center",
  ].join(" "),
  emptyIcon: [
    "mb-4",
    "size-9",
    "text-muted-foreground",
  ].join(" "),
  emptyTitle: [
    "font-semibold",
    "text-foreground",
  ].join(" "),
  emptyBody: [
    "mt-2",
    "max-w-sm",
    "text-sm",
    "leading-6",
    "text-muted-foreground",
  ].join(" "),
  list: [
    "mt-6",
    "flex",
    "max-h-[28rem]",
    "flex-col",
    "gap-3",
    "overflow-y-auto",
  ].join(" "),
  footer: [
    "mt-6",
    "flex",
    "flex-col",
    "gap-3",
    "border-t",
    "border-border",
    "pt-5",
    "sm:flex-row",
    "sm:items-center",
    "sm:justify-between",
  ].join(" "),
  actions: [
    "flex",
    "flex-wrap",
    "gap-3",
  ].join(" "),
  availability: [
    "text-xs",
    "leading-5",
    "text-muted-foreground",
  ].join(" "),
} as const;
